//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS5.Resources.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lenguaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lenguaje() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HS5.Resources.Idiomas.Lenguaje", typeof(Lenguaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AVAILABLE RATES.
        /// </summary>
        public static string availRates {
            get {
                return ResourceManager.GetString("availRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Sections:.
        /// </summary>
        public static string availSect {
            get {
                return ResourceManager.GetString("availSect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERASE RATE.
        /// </summary>
        public static string brnEraseRate {
            get {
                return ResourceManager.GetString("brnEraseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE CHANGES.
        /// </summary>
        public static string brnSC {
            get {
                return ResourceManager.GetString("brnSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Image .
        /// </summary>
        public static string btnAddImage {
            get {
                return ResourceManager.GetString("btnAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTOSIMILE.
        /// </summary>
        public static string btnAutoSM {
            get {
                return ResourceManager.GetString("btnAutoSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Analysis.
        /// </summary>
        public static string btnCAna {
            get {
                return ResourceManager.GetString("btnCAna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COPY.
        /// </summary>
        public static string btnCopy {
            get {
                return ResourceManager.GetString("btnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUPLICATE.
        /// </summary>
        public static string btnD {
            get {
                return ResourceManager.GetString("btnD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE REMEDY.
        /// </summary>
        public static string btnDelRem {
            get {
                return ResourceManager.GetString("btnDelRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE THERAPY.
        /// </summary>
        public static string btnDelTherap {
            get {
                return ResourceManager.GetString("btnDelTherap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECT TREATMENT.
        /// </summary>
        public static string btnDirectT {
            get {
                return ResourceManager.GetString("btnDirectT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUPLICATE REMEDY .
        /// </summary>
        public static string btnDupli {
            get {
                return ResourceManager.GetString("btnDupli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERASE ECS.
        /// </summary>
        public static string btnErase {
            get {
                return ResourceManager.GetString("btnErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERASE.
        /// </summary>
        public static string btnEraseNorm {
            get {
                return ResourceManager.GetString("btnEraseNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find PGR.
        /// </summary>
        public static string btnFinPgre {
            get {
                return ResourceManager.GetString("btnFinPgre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GET RATE.
        /// </summary>
        public static string btnGetRate {
            get {
                return ResourceManager.GetString("btnGetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMPRINT.
        /// </summary>
        public static string btnImp {
            get {
                return ResourceManager.GetString("btnImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEUTRALIZE.
        /// </summary>
        public static string btnNeutralize {
            get {
                return ResourceManager.GetString("btnNeutralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Analysis | Reanalysis.
        /// </summary>
        public static string btnNewAnal {
            get {
                return ResourceManager.GetString("btnNewAnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW BROADCASTING.
        /// </summary>
        public static string btnNewBroad {
            get {
                return ResourceManager.GetString("btnNewBroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW CATEGORY.
        /// </summary>
        public static string btnNewCat {
            get {
                return ResourceManager.GetString("btnNewCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW RATE.
        /// </summary>
        public static string btnNewRate {
            get {
                return ResourceManager.GetString("btnNewRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW REMEDY.
        /// </summary>
        public static string btnNewRem {
            get {
                return ResourceManager.GetString("btnNewRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW SUB CATEGORY.
        /// </summary>
        public static string btnNewSubCat {
            get {
                return ResourceManager.GetString("btnNewSubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEW THERAPY.
        /// </summary>
        public static string btnNewTherap {
            get {
                return ResourceManager.GetString("btnNewTherap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NONE.
        /// </summary>
        public static string btnNone {
            get {
                return ResourceManager.GetString("btnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAUSE.
        /// </summary>
        public static string btnPause {
            get {
                return ResourceManager.GetString("btnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a POTENTIATION.
        /// </summary>
        public static string btnPotent {
            get {
                return ResourceManager.GetString("btnPotent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QR-CODE.
        /// </summary>
        public static string btnQR {
            get {
                return ResourceManager.GetString("btnQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reanalysis.
        /// </summary>
        public static string btnReana {
            get {
                return ResourceManager.GetString("btnReana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THERAPY REPORT.
        /// </summary>
        public static string btnRepTherap {
            get {
                return ResourceManager.GetString("btnRepTherap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESUME.
        /// </summary>
        public static string btnResume {
            get {
                return ResourceManager.GetString("btnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE TO ECS.
        /// </summary>
        public static string btnSaveEcs {
            get {
                return ResourceManager.GetString("btnSaveEcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE ECS TO DATABASE.
        /// </summary>
        public static string btnSaveEcsDB {
            get {
                return ResourceManager.GetString("btnSaveEcsDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save patient.
        /// </summary>
        public static string btnSaveP {
            get {
                return ResourceManager.GetString("btnSaveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save PGR to  ECS.
        /// </summary>
        public static string btnSavePGR {
            get {
                return ResourceManager.GetString("btnSavePGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE THERAPY.
        /// </summary>
        public static string btnSaveT {
            get {
                return ResourceManager.GetString("btnSaveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USE.
        /// </summary>
        public static string btnUse {
            get {
                return ResourceManager.GetString("btnUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories .
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATE.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BROADCASTING CONTROL.
        /// </summary>
        public static string headBroad {
            get {
                return ResourceManager.GetString("headBroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string headComments {
            get {
                return ResourceManager.GetString("headComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hereditary.
        /// </summary>
        public static string headeHedit {
            get {
                return ResourceManager.GetString("headeHedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address Details.
        /// </summary>
        public static string headerAdd {
            get {
                return ResourceManager.GetString("headerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adresses.
        /// </summary>
        public static string headerAddresses {
            get {
                return ResourceManager.GetString("headerAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string HeaderAdreess {
            get {
                return ResourceManager.GetString("HeaderAdreess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analysis&apos; Search.
        /// </summary>
        public static string headerAnalysisearch {
            get {
                return ResourceManager.GetString("headerAnalysisearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Records.
        /// </summary>
        public static string headerListRecords {
            get {
                return ResourceManager.GetString("headerListRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIST OF RECENT THERAPIES.
        /// </summary>
        public static string headerListReport {
            get {
                return ResourceManager.GetString("headerListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient&apos;s Search:.
        /// </summary>
        public static string HeaderPatientSearch {
            get {
                return ResourceManager.GetString("HeaderPatientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Records.
        /// </summary>
        public static string HeaderRecords {
            get {
                return ResourceManager.GetString("HeaderRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register New Patient .
        /// </summary>
        public static string HeaderRP {
            get {
                return ResourceManager.GetString("HeaderRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUNNING (RIGTH NOW).
        /// </summary>
        public static string headerRun {
            get {
                return ResourceManager.GetString("headerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THERAPY SEARCH .
        /// </summary>
        public static string headerTherapSearch {
            get {
                return ResourceManager.GetString("headerTherapSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ON HOLD.
        /// </summary>
        public static string headHold {
            get {
                return ResourceManager.GetString("headHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIST OF COMMENTS.
        /// </summary>
        public static string headListComments {
            get {
                return ResourceManager.GetString("headListComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIST OF (NON) PATHOLOGICAL.
        /// </summary>
        public static string headListNonPath {
            get {
                return ResourceManager.GetString("headListNonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIST OF PATHOLOGICAL.
        /// </summary>
        public static string headListPatholog {
            get {
                return ResourceManager.GetString("headListPatholog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Non Pathological.
        /// </summary>
        public static string headNonPath {
            get {
                return ResourceManager.GetString("headNonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pathological.
        /// </summary>
        public static string headPatho {
            get {
                return ResourceManager.GetString("headPatho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analysis | Re-analysis .
        /// </summary>
        public static string headReana {
            get {
                return ResourceManager.GetString("headReana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIST OF RECENT ANALYSIS.
        /// </summary>
        public static string headRecentListAna {
            get {
                return ResourceManager.GetString("headRecentListAna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REMEDY SEARCH.
        /// </summary>
        public static string headRemSearch {
            get {
                return ResourceManager.GetString("headRemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string inputAll {
            get {
                return ResourceManager.GetString("inputAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By Analysis.
        /// </summary>
        public static string inputByAna {
            get {
                return ResourceManager.GetString("inputByAna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By User.
        /// </summary>
        public static string inputByUser {
            get {
                return ResourceManager.GetString("inputByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of the Rate.
        /// </summary>
        public static string inputMessBox1 {
            get {
                return ResourceManager.GetString("inputMessBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting Rate.
        /// </summary>
        public static string inputMessHead1 {
            get {
                return ResourceManager.GetString("inputMessHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a College School.
        /// </summary>
        public static string itemCollSchool {
            get {
                return ResourceManager.GetString("itemCollSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elementary School.
        /// </summary>
        public static string itemElemSchool {
            get {
                return ResourceManager.GetString("itemElemSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junior High School.
        /// </summary>
        public static string itemJunSchool {
            get {
                return ResourceManager.GetString("itemJunSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master&apos;s Degree.
        /// </summary>
        public static string itemMaster {
            get {
                return ResourceManager.GetString("itemMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a University.
        /// </summary>
        public static string itemUniversity {
            get {
                return ResourceManager.GetString("itemUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avenue:.
        /// </summary>
        public static string labelAvenue {
            get {
                return ResourceManager.GetString("labelAvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth Date:.
        /// </summary>
        public static string labelBithDate {
            get {
                return ResourceManager.GetString("labelBithDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories.
        /// </summary>
        public static string labelCat {
            get {
                return ResourceManager.GetString("labelCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color Selected:.
        /// </summary>
        public static string labelColSel {
            get {
                return ResourceManager.GetString("labelColSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMBINATED RATES:.
        /// </summary>
        public static string labelCombiRate {
            get {
                return ResourceManager.GetString("labelCombiRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country:.
        /// </summary>
        public static string labelCountry {
            get {
                return ResourceManager.GetString("labelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country or Shire:.
        /// </summary>
        public static string labelCS {
            get {
                return ResourceManager.GetString("labelCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        public static string labelDataBase {
            get {
                return ResourceManager.GetString("labelDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date:.
        /// </summary>
        public static string labelDate {
            get {
                return ResourceManager.GetString("labelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description:.
        /// </summary>
        public static string labelDescrip {
            get {
                return ResourceManager.GetString("labelDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ext:.
        /// </summary>
        public static string labelExt {
            get {
                return ResourceManager.GetString("labelExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name: .
        /// </summary>
        public static string labelFName {
            get {
                return ResourceManager.GetString("labelFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gennder:.
        /// </summary>
        public static string labelGender {
            get {
                return ResourceManager.GetString("labelGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rates Included:.
        /// </summary>
        public static string labelInclude {
            get {
                return ResourceManager.GetString("labelInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name:.
        /// </summary>
        public static string labelLastName {
            get {
                return ResourceManager.GetString("labelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REMEDY.
        /// </summary>
        public static string labelMayRem {
            get {
                return ResourceManager.GetString("labelMayRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Middle Name:.
        /// </summary>
        public static string labelMName {
            get {
                return ResourceManager.GetString("labelMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num:.
        /// </summary>
        public static string labelNum {
            get {
                return ResourceManager.GetString("labelNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order By.
        /// </summary>
        public static string labelOrder {
            get {
                return ResourceManager.GetString("labelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal Frenquecy:.
        /// </summary>
        public static string labelPersonal {
            get {
                return ResourceManager.GetString("labelPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        public static string labelPhone {
            get {
                return ResourceManager.GetString("labelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PORTS:.
        /// </summary>
        public static string labelPorts {
            get {
                return ResourceManager.GetString("labelPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Related Analysis:.
        /// </summary>
        public static string labelRAN {
            get {
                return ResourceManager.GetString("labelRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remedy.
        /// </summary>
        public static string labelRemedy {
            get {
                return ResourceManager.GetString("labelRemedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remedy:.
        /// </summary>
        public static string labelRM {
            get {
                return ResourceManager.GetString("labelRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State:.
        /// </summary>
        public static string labelSatet {
            get {
                return ResourceManager.GetString("labelSatet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a School Degree:.
        /// </summary>
        public static string LabelSchool {
            get {
                return ResourceManager.GetString("LabelSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search in Database:.
        /// </summary>
        public static string labelSearchDatabase {
            get {
                return ResourceManager.GetString("labelSearchDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEARCH (RATE):.
        /// </summary>
        public static string labelSearchRate {
            get {
                return ResourceManager.GetString("labelSearchRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select the appropiate PORT in order to continue:.
        /// </summary>
        public static string labelSelectPort {
            get {
                return ResourceManager.GetString("labelSelectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Street:.
        /// </summary>
        public static string labelStreet {
            get {
                return ResourceManager.GetString("labelStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub-Categories.
        /// </summary>
        public static string labelSubCat {
            get {
                return ResourceManager.GetString("labelSubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Therapy:.
        /// </summary>
        public static string labelTherap {
            get {
                return ResourceManager.GetString("labelTherap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title:.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View:.
        /// </summary>
        public static string labelView {
            get {
                return ResourceManager.GetString("labelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code:.
        /// </summary>
        public static string labelZpCode {
            get {
                return ResourceManager.GetString("labelZpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analysis.
        /// </summary>
        public static string MenuAnalysis {
            get {
                return ResourceManager.GetString("MenuAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broadcasting.
        /// </summary>
        public static string MenuBroad {
            get {
                return ResourceManager.GetString("MenuBroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chromotherapy.
        /// </summary>
        public static string MenuChromo {
            get {
                return ResourceManager.GetString("MenuChromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient.
        /// </summary>
        public static string MenuPatient {
            get {
                return ResourceManager.GetString("MenuPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remedies and Homoepathy .
        /// </summary>
        public static string MenuRemedies {
            get {
                return ResourceManager.GetString("MenuRemedies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only Numbers are allowed.
        /// </summary>
        public static string messageError {
            get {
                return ResourceManager.GetString("messageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please write the Rate&apos;s name!.
        /// </summary>
        public static string messageError1 {
            get {
                return ResourceManager.GetString("messageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only integer numbers are allowed in the scheduling process.
        /// </summary>
        public static string messageError10 {
            get {
                return ResourceManager.GetString("messageError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the type of scheduling to continue!....
        /// </summary>
        public static string messageError11 {
            get {
                return ResourceManager.GetString("messageError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;During&apos; and &apos;Every&apos; cannot have that values!.
        /// </summary>
        public static string messageError12 {
            get {
                return ResourceManager.GetString("messageError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input the estimate time to continue.
        /// </summary>
        public static string messageError13 {
            get {
                return ResourceManager.GetString("messageError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select the type of treatment!.
        /// </summary>
        public static string messageError14 {
            get {
                return ResourceManager.GetString("messageError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please write a treatment&apos;s name before continue!.
        /// </summary>
        public static string messageError15 {
            get {
                return ResourceManager.GetString("messageError15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a patient in order to continue!....
        /// </summary>
        public static string messageError16 {
            get {
                return ResourceManager.GetString("messageError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an analysis before continue with a re-analysis.
        /// </summary>
        public static string messageError17 {
            get {
                return ResourceManager.GetString("messageError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an analysis before erasing a record.
        /// </summary>
        public static string messageError18 {
            get {
                return ResourceManager.GetString("messageError18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter another name for the analysis-is already in use.
        /// </summary>
        public static string messageError19 {
            get {
                return ResourceManager.GetString("messageError19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a therapy before eliminating it!.
        /// </summary>
        public static string messageError2 {
            get {
                return ResourceManager.GetString("messageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a patient before performing the analysis.
        /// </summary>
        public static string messageError20 {
            get {
                return ResourceManager.GetString("messageError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please write an analysis name before continue....
        /// </summary>
        public static string messageError21 {
            get {
                return ResourceManager.GetString("messageError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a patient to see the analysis!.
        /// </summary>
        public static string messageError22 {
            get {
                return ResourceManager.GetString("messageError22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First select it  a code before execute the  operation .
        /// </summary>
        public static string messageError23 {
            get {
                return ResourceManager.GetString("messageError23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please write the Rate&apos;s name!.
        /// </summary>
        public static string messageError24 {
            get {
                return ResourceManager.GetString("messageError24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a main category first and a sub-category in order to add a new rate on the database!.
        /// </summary>
        public static string messageError25 {
            get {
                return ResourceManager.GetString("messageError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a color before continuing.
        /// </summary>
        public static string messageError26 {
            get {
                return ResourceManager.GetString("messageError26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot save a therapy without a single combinated rate!.
        /// </summary>
        public static string messageError27 {
            get {
                return ResourceManager.GetString("messageError27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You haven&apos;t written anything, please write down one.
        /// </summary>
        public static string messageError28 {
            get {
                return ResourceManager.GetString("messageError28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a sub-category before deleting!.
        /// </summary>
        public static string messageError29 {
            get {
                return ResourceManager.GetString("messageError29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Please fill in    all fields before to  continue! .
        /// </summary>
        public static string messageError3 {
            get {
                return ResourceManager.GetString("messageError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a category before deleting!.
        /// </summary>
        public static string messageError30 {
            get {
                return ResourceManager.GetString("messageError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please write a name for the remedy!.
        /// </summary>
        public static string messageError31 {
            get {
                return ResourceManager.GetString("messageError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an item before continuing.
        /// </summary>
        public static string messageError4 {
            get {
                return ResourceManager.GetString("messageError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliga una ubicación antes de continuar!...
        /// </summary>
        public static string messageError5 {
            get {
                return ResourceManager.GetString("messageError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Chose a treatment  before continuing!...
        /// </summary>
        public static string messageError6 {
            get {
                return ResourceManager.GetString("messageError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a treatment first!...
        /// </summary>
        public static string messageError7 {
            get {
                return ResourceManager.GetString("messageError7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select an element to continue!.
        /// </summary>
        public static string messageError8 {
            get {
                return ResourceManager.GetString("messageError8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please type an analysis name before continuing.
        /// </summary>
        public static string messageError9 {
            get {
                return ResourceManager.GetString("messageError9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a information.
        /// </summary>
        public static string messageHeadInf {
            get {
                return ResourceManager.GetString("messageHeadInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        public static string messageHeadQ {
            get {
                return ResourceManager.GetString("messageHeadQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string messageHeadWarning {
            get {
                return ResourceManager.GetString("messageHeadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a category to continue!.
        /// </summary>
        public static string messageInf1 {
            get {
                return ResourceManager.GetString("messageInf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to include the &apos;Sequence&apos; in the erasing process?.
        /// </summary>
        public static string messageQustion1 {
            get {
                return ResourceManager.GetString("messageQustion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want  to  change the language ?.
        /// </summary>
        public static string messageWarning {
            get {
                return ResourceManager.GetString("messageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a main category first and a sub-category in order to get a new rate on the database!.
        /// </summary>
        public static string messageWarning2 {
            get {
                return ResourceManager.GetString("messageWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a category and subcategory first in order to continue!.
        /// </summary>
        public static string messageWarning3 {
            get {
                return ResourceManager.GetString("messageWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select the language to the  system:.
        /// </summary>
        public static string messOptLan {
            get {
                return ResourceManager.GetString("messOptLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of the Analysis:.
        /// </summary>
        public static string nameAnalysis {
            get {
                return ResourceManager.GetString("nameAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manuel.
        /// </summary>
        public static string NavItem {
            get {
                return ResourceManager.GetString("NavItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string optLangEn {
            get {
                return ResourceManager.GetString("optLangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string optLangEs {
            get {
                return ResourceManager.GetString("optLangEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PATIENT&apos;S GENDER.
        /// </summary>
        public static string patGender {
            get {
                return ResourceManager.GetString("patGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Patient&apos;s list.
        /// </summary>
        public static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESET COLORS.
        /// </summary>
        public static string resetC {
            get {
                return ResourceManager.GetString("resetC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RETURN  TO RECENT THERAPIES.
        /// </summary>
        public static string returnTheRecent {
            get {
                return ResourceManager.GetString("returnTheRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BEGGING TIME.
        /// </summary>
        public static string tableBegTime {
            get {
                return ResourceManager.GetString("tableBegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPLEMENTARY.
        /// </summary>
        public static string tableComp {
            get {
                return ResourceManager.GetString("tableComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DESCRIPTION.
        /// </summary>
        public static string tableDes {
            get {
                return ResourceManager.GetString("tableDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DURATION.
        /// </summary>
        public static string tableDuration {
            get {
                return ResourceManager.GetString("tableDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a END DATE.
        /// </summary>
        public static string tableEndDate {
            get {
                return ResourceManager.GetString("tableEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEVEL.
        /// </summary>
        public static string tableLevel {
            get {
                return ResourceManager.GetString("tableLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a METHOD.
        /// </summary>
        public static string tableMethod {
            get {
                return ResourceManager.GetString("tableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MISSING TIME.
        /// </summary>
        public static string tableMissing {
            get {
                return ResourceManager.GetString("tableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NAME.
        /// </summary>
        public static string tableName {
            get {
                return ResourceManager.GetString("tableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ANALYSIS NAME.
        /// </summary>
        public static string tableNameAna {
            get {
                return ResourceManager.GetString("tableNameAna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PATIENT&apos;S NAME .
        /// </summary>
        public static string tableNameP {
            get {
                return ResourceManager.GetString("tableNameP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PATIENT.
        /// </summary>
        public static string tablePat {
            get {
                return ResourceManager.GetString("tablePat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string TablePCreate {
            get {
                return ResourceManager.GetString("TablePCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE.
        /// </summary>
        public static string TablePDelete {
            get {
                return ResourceManager.GetString("TablePDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a POTENCY.
        /// </summary>
        public static string tablePotency {
            get {
                return ResourceManager.GetString("tablePotency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RATE.
        /// </summary>
        public static string tableRate {
            get {
                return ResourceManager.GetString("tableRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO.
        /// </summary>
        public static string tableRateTip {
            get {
                return ResourceManager.GetString("tableRateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START DATE.
        /// </summary>
        public static string tableStartDate {
            get {
                return ResourceManager.GetString("tableStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TREATMENT.
        /// </summary>
        public static string tableTreat {
            get {
                return ResourceManager.GetString("tableTreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animal.
        /// </summary>
        public static string valAnimal {
            get {
                return ResourceManager.GetString("valAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string valFemale {
            get {
                return ResourceManager.GetString("valFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string valMale {
            get {
                return ResourceManager.GetString("valMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plant and Soil.
        /// </summary>
        public static string valPlant {
            get {
                return ResourceManager.GetString("valPlant", resourceCulture);
            }
        }
    }
}
