//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS5.Resources.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lenguaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lenguaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HS5.Resources.Idiomas.Lenguaje", typeof(Lenguaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image .
        /// </summary>
        public static string btnAddImage {
            get {
                return ResourceManager.GetString("btnAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Analysis.
        /// </summary>
        public static string btnCAna {
            get {
                return ResourceManager.GetString("btnCAna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find PGR.
        /// </summary>
        public static string btnFinPgre {
            get {
                return ResourceManager.GetString("btnFinPgre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Analysis | Reanalysis.
        /// </summary>
        public static string btnNewAnal {
            get {
                return ResourceManager.GetString("btnNewAnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save patient.
        /// </summary>
        public static string btnSaveP {
            get {
                return ResourceManager.GetString("btnSaveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save PGR to  ECS.
        /// </summary>
        public static string btnSavePGR {
            get {
                return ResourceManager.GetString("btnSavePGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories .
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string headComments {
            get {
                return ResourceManager.GetString("headComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hereditary.
        /// </summary>
        public static string headeHedit {
            get {
                return ResourceManager.GetString("headeHedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        public static string headerAdd {
            get {
                return ResourceManager.GetString("headerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses.
        /// </summary>
        public static string headerAddresses {
            get {
                return ResourceManager.GetString("headerAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string HeaderAdreess {
            get {
                return ResourceManager.GetString("HeaderAdreess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis&apos; Search.
        /// </summary>
        public static string headerAnalysisearch {
            get {
                return ResourceManager.GetString("headerAnalysisearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Records.
        /// </summary>
        public static string headerListRecords {
            get {
                return ResourceManager.GetString("headerListRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Search.
        /// </summary>
        public static string HeaderPatientSearch {
            get {
                return ResourceManager.GetString("HeaderPatientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string HeaderRecords {
            get {
                return ResourceManager.GetString("HeaderRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Patient .
        /// </summary>
        public static string HeaderRP {
            get {
                return ResourceManager.GetString("HeaderRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Non Pathologcal.
        /// </summary>
        public static string headNonPath {
            get {
                return ResourceManager.GetString("headNonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathological.
        /// </summary>
        public static string headPatho {
            get {
                return ResourceManager.GetString("headPatho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis | Reanalysis .
        /// </summary>
        public static string headReana {
            get {
                return ResourceManager.GetString("headReana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenue:.
        /// </summary>
        public static string labelAvenue {
            get {
                return ResourceManager.GetString("labelAvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date:.
        /// </summary>
        public static string labelBithDate {
            get {
                return ResourceManager.GetString("labelBithDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string labelCountry {
            get {
                return ResourceManager.GetString("labelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country or Shire:.
        /// </summary>
        public static string labelCS {
            get {
                return ResourceManager.GetString("labelCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string labelDescrip {
            get {
                return ResourceManager.GetString("labelDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext:.
        /// </summary>
        public static string labelExt {
            get {
                return ResourceManager.GetString("labelExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name: .
        /// </summary>
        public static string labelFName {
            get {
                return ResourceManager.GetString("labelFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gennder:.
        /// </summary>
        public static string labelGender {
            get {
                return ResourceManager.GetString("labelGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string labelLastName {
            get {
                return ResourceManager.GetString("labelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name:.
        /// </summary>
        public static string labelMName {
            get {
                return ResourceManager.GetString("labelMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num:.
        /// </summary>
        public static string labelNum {
            get {
                return ResourceManager.GetString("labelNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Frenquecy:.
        /// </summary>
        public static string labelPersonal {
            get {
                return ResourceManager.GetString("labelPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string labelPhone {
            get {
                return ResourceManager.GetString("labelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Analysis.
        /// </summary>
        public static string labelRAN {
            get {
                return ResourceManager.GetString("labelRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string labelSatet {
            get {
                return ResourceManager.GetString("labelSatet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Degree:.
        /// </summary>
        public static string LabelSchool {
            get {
                return ResourceManager.GetString("LabelSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string labelStreet {
            get {
                return ResourceManager.GetString("labelStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code:.
        /// </summary>
        public static string labelZpCode {
            get {
                return ResourceManager.GetString("labelZpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string MenuAnalysis {
            get {
                return ResourceManager.GetString("MenuAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcasting.
        /// </summary>
        public static string MenuBroad {
            get {
                return ResourceManager.GetString("MenuBroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromotherapy.
        /// </summary>
        public static string MenuChromo {
            get {
                return ResourceManager.GetString("MenuChromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string MenuPatient {
            get {
                return ResourceManager.GetString("MenuPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remedies and Homoepathy .
        /// </summary>
        public static string MenuRemedies {
            get {
                return ResourceManager.GetString("MenuRemedies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Analysis:.
        /// </summary>
        public static string nameAnalysis {
            get {
                return ResourceManager.GetString("nameAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuel.
        /// </summary>
        public static string NavItem {
            get {
                return ResourceManager.GetString("NavItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patinet&apos;s list.
        /// </summary>
        public static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string tableName {
            get {
                return ResourceManager.GetString("tableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisys Name.
        /// </summary>
        public static string tableNameAna {
            get {
                return ResourceManager.GetString("tableNameAna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Name.
        /// </summary>
        public static string tableNameP {
            get {
                return ResourceManager.GetString("tableNameP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TablePCreate {
            get {
                return ResourceManager.GetString("TablePCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        public static string TablePDelete {
            get {
                return ResourceManager.GetString("TablePDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal.
        /// </summary>
        public static string valAnimal {
            get {
                return ResourceManager.GetString("valAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string valFemale {
            get {
                return ResourceManager.GetString("valFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string valMale {
            get {
                return ResourceManager.GetString("valMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant and Soil.
        /// </summary>
        public static string valPlant {
            get {
                return ResourceManager.GetString("valPlant", resourceCulture);
            }
        }
    }
}
